### ISSUE TITLE
ERROR: File "setup.py" not found. when pip installing

### ISSUE THREAD

**Issue by isspid** [ocrmypdf/OCRmyPDF-EasyOCR#1]
Hi,

firstly thanks a lot for the development, EasyOCR has been performing better for my usecase so it's very nice to have it integrated into OCRmyPDF, another great project.

I am having trouble making it run though, and I am not sure whether this is a bug or simply me not knowing how to run a plugin with OCRmyPDF. 

I have cloned https://github.com/ocrmypdf/OCRmyPDF-EasyOCR, then I cd into the directory and then run
```bash
python -m venv .venv
.venv\Scripts\activate
pip install -e .
```
At this point I get the error
```
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: C:\Users\istaka\OneDrive - Schüßler-Plan GmbH\Dev\OCRmyPDF-EasyOCR
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

Am I doing something wrong?

**Comment by isspid** [comment]
My mistake was not having installed ocrmypdf first. 

So for everybody reading this: first install ocrmypdf with `pip install ocrmypdf` and then run 
`pip install -e .`

Also, another tip, from what I understood version 3.10 of Python has to be installed but I am not 100% sure on this.

**Comment by jbarlow83** [comment]
I think the first Python (or setuptools etc) you tried to install with it was fairly old and didn't recognize the Python 3.10 requirement or modern pyproject.toml.
