### ISSUE TITLE
Error: NotImplementedError: EasyOCR does not support hOCR output

### ISSUE THREAD

**Issue by OctopusET** [ocrmypdf/OCRmyPDF-EasyOCR#10]
I got this error when I do `ocrmypdf input.pdf output.pdf`
I'm pretty sure it's intended result, but is there any way to try this plugin?

**Comment by jbarlow83** [comment]
`--output-type pdf` will be needed until I develop to not need sleep so I can work on open source when I should be sleeping....

**Comment by Nick468** [comment]
Hi, having the same problem. Adding `--output-type pdf` does not change anything. Running `ocrmypdf input.pdf output.pdf --output-type pdf -l eng` does not work. Am I doing something wrong or should this work?
The only way I could get this plugin to run is by adding `--pdf-renderer sandwich`. Is this the intended way? Using this renderer seems to modify embedded images by oversharpening them. 
Any help in getting this to run properly would be appreciated, as the text recognition is so much better than the default!

**Comment by StillSleeping-Bye** [comment]
Hi , i'm having the same error, i've already tried to add `--output-type pdf` but nothing change

**Comment by jbarlow83** [comment]
As the error message says, the feature is not implemented.
