### ISSUE TITLE
italic text in Bulgarian is not recognised

### ISSUE THREAD

**Issue by varna9000** [ocrmypdf/OCRmyPDF-EasyOCR#14]
It appears easyOCR model for Bulgarian lang is not good. It doesn't recognise italic font and produces garbage. Bold and normal fonts are ok. Underlined font produces underscore on spaces between words.

How do you switch back to tesseract for a particular language?

**Comment by jbarlow83** [comment]
You would have to create a separate virtual environment without easyocr installed and then direct the OCR job to the desired engine. Or modify this plugin to defer to tesseract for Bulgarian instead of using easyocr.

At the moment there's no way to do this without some coding.

**Comment by jbarlow83** [comment]
You could also report the problematic image to the developers of EasyOCR.
