### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by deajan** [ocrmypdf/OCRmyPDF-EasyOCR#8]
Hello,

I'm currently tweaking [paperless-ngx](https://github.com/paperless-ngx/paperless-ngx), which already uses OCRMyPDF, to use EasyOCR.
Would you mind releasing a PyPI version of this package, so it can easily integrate into a pip file ?

Thanks.

**Comment by jbarlow83** [comment]
I will as it becomes more mature.

For now you can use a URI specifier for example
```
ocrmypdf-easyocr @ https://github.com/ocrmypdf/OCRmyPDF-EasyOCR/archive/refs/heads/main.zip
```

**Comment by deajan** [comment]
Understandable, that's already what I do, but pointing to my repo with a couple of changes.

**Comment by jbarlow83** [comment]
Now serving on PyPI

**Comment by deajan** [comment]
Does the PyPI version include billiard requirements perhaps, or is it an optional setup task ?

**Comment by jbarlow83** [comment]
billiard is imported if it is installed, but is not listed as a requirement.

**Comment by deajan** [comment]
Makes sense. Thanks.
